name: frontend
on:
  push:
    branches: [main]
    paths: ['frontend/**', 'README.md']
  pull_request:
    branches: [main]
    paths: ['frontend/**']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm -C frontend install --frozen-lockfile=false
      - run: pnpm -C frontend build || pnpm -C frontend tsc --noEmit
